# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/maximilianpalme/PycharmProjects/obdPi_palme/gui/src/dashboard_palme.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(340, 280, 160, 16))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 310, 81, 26))
        self.pushButton.setObjectName("pushButton")
        self.oil_temp_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.oil_temp_gb.setGeometry(QtCore.QRect(0, 0, 240, 240))
        self.oil_temp_gb.setObjectName("oil_temp_gb")
        self.oil_temp_bg_label = QtWidgets.QLabel(self.oil_temp_gb)
        self.oil_temp_bg_label.setGeometry(QtCore.QRect(0, 0, 240, 240))
        self.oil_temp_bg_label.setText("")
        self.oil_temp_bg_label.setPixmap(QtGui.QPixmap("/Users/maximilianpalme/PycharmProjects/obdPi_palme/gui/src/../oil_temp_pictures/bg_240x240px.png"))
        self.oil_temp_bg_label.setScaledContents(True)
        self.oil_temp_bg_label.setObjectName("oil_temp_bg_label")
        self.oil_temp_value = QtWidgets.QLabel(self.oil_temp_gb)
        self.oil_temp_value.setGeometry(QtCore.QRect(90, 185, 61, 41))
        self.oil_temp_value.setMidLineWidth(-1)
        self.oil_temp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.oil_temp_value.setObjectName("oil_temp_value")
        self.oil_temp_gauge = QtWidgets.QLabel(self.oil_temp_gb)
        self.oil_temp_gauge.setGeometry(QtCore.QRect(11, 11, 218, 170))
        self.oil_temp_gauge.setText("")
        self.oil_temp_gauge.setPixmap(QtGui.QPixmap("/Users/maximilianpalme/PycharmProjects/obdPi_palme/gui/src/../oil_temp_pictures/temp_cold.png"))
        self.oil_temp_gauge.setScaledContents(False)
        self.oil_temp_gauge.setObjectName("oil_temp_gauge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPage_1 = QtWidgets.QMenu(self.menubar)
        self.menuPage_1.setObjectName("menuPage_1")
        self.menuPage_2 = QtWidgets.QMenu(self.menubar)
        self.menuPage_2.setObjectName("menuPage_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPage_1.menuAction())
        self.menubar.addAction(self.menuPage_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Page 2"))
        self.oil_temp_gb.setTitle(_translate("MainWindow", "GroupBox"))
        self.oil_temp_value.setText(_translate("MainWindow", "0"))
        self.menuPage_1.setTitle(_translate("MainWindow", "Page 1"))
        self.menuPage_2.setTitle(_translate("MainWindow", "Page 2"))
